python drive/MyDrive/JointIDSF/main.py --task vi-atis-fix \
                  --model_type phobert \
                  --model_dir test_run \
                  --data_dir drive/MyDrive/JointIDSF/data \
                  --do_train \
                  --do_eval \
                  --seed 1 \
                  --tuning_metric mean_intent_slot \
                  --save_steps 140 \
                  --logging_steps 140 \
                  --num_train_epochs 50 \
                  --use_intent_context_attention \
                  --attention_embedding_size 200 \
                  --use_crf \
                  --embedding_type soft \
                  --intent_loss_coef 0.5 \
                  --early_stopping 30 \
                  --token_level word \
                  --learning_rate 5e-5 